apiVersion: v1
kind: Service
metadata:
  name: unleash
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 4242
      targetPort: 4242
      name: http
  selector:
    app: unleash
