apiVersion: v1
kind: ConfigMap
metadata:
  name: koku-config
  namespace: {{ .Values.namespace }}
data:
  DATABASE_SERVICE_NAME: "{{ .Values.database.databaseServiceName }}"
  DATABASE_ENGINE: "{{ .Values.database.databaseEngine }}"
  DATABASE_NAME: "{{ .Values.database.databaseName }}"
  PGADMIN_EMAIL: "postgres@local.dev"
  PGADMIN_PASSWORD: "postgres"
  PGADMIN_PORT: "8432"
  POSTGRES_SQL_SERVICE_HOST: "{{ tpl .Values.database.postgresSQLServiceHost . }}"
  POSTGRES_SQL_SERVICE_PORT: "{{ .Values.database.postgresSQLServicePort }}"
  DATABASE_USER: "{{ .Values.database.databaseUser }}"
  DATABASE_ADMIN: "{{ .Values.database.databaseAdmin }}"
  DATABASE_PASSWORD: "{{ .Values.database.databasePassword }}"
  HIVE_DATABASE_NAME: "{{ .Values.database.hiveDatabaseName }}"
  HIVE_DATABASE_USER: "{{ .Values.database.hiveDatabaseUser }}"
  HIVE_DATABASE_PASSWORD: "{{ .Values.database.hiveDatabasePassword }}"
  DEBUG_ATTACH: "False"
  DEVELOPMENT: "True"
  PROMETHEUS_MULTIPROC_DIR: "/tmp"
  CURRENCY_URL: "https://open.er-api.com/v6/latest/USD"
  UNLEASH_ADMIN_TOKEN: "{{ .Values.unleash.adminToken }}"
  UNLEASH_TOKEN: "{{ .Values.unleash.token }}"
  UNLEASH_PAT: "{{ .Values.unleash.patToken }}"
  UNLEASH_HOST: "unleash.{{ .Values.namespace }}.svc.cluster.local"
  POLLING_TIMER: "60"
  PROCESSING_WAIT_TIMER: "3"
  LARGE_PROCESSING_WAIT_TIMER: "7"
  MAX_GROUP_BY_OVERRIDE: "3"
  TAG_ENABLED_LIMIT: "200"
  DELAYED_TASK_TIME: "30"
  DELAYED_TASK_POLLING_MINUTES: "5"
  SKIP_MINIO_DATA_DELETION: "False"
  AWS_SHARED_CREDENTIALS_FILE: "/etc/credentials/aws"
  AWS_RESOURCE_NAME: "YOUR_COST_MANAGEMENT_AWS_ARN"
  SCHEMA_SUFFIX: ""
  TRINO_S3A_OR_S3: "s3a"
  HIVE_PROPERTIES_FILE: "hive.properties"
  GLUE_PROPERTIES_FILE: "glue.properties"
  MINIO_ENDPOINT: "http://minio.{{ .Values.namespace }}.svc.cluster.local:9000"
  S3_ENDPOINT: "http://minio.{{ .Values.namespace }}.svc.cluster.local:9000"
  S3_ACCESS_KEY: "kokuminioaccess"
  S3_SECRET: "kokuminiosecret"
  AWS_ACCESS_KEY_ID: "{{ .Values.credentials.awsAccessKeyId }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.credentials.awsSecretAccessKey }}"
  S3_BUCKET_NAME: "koku-bucket"
  S3_BUCKET_NAME_OCP_INGRESS: "ocp-ingress"
  S3_REGION: "us-east-1"
  GOOGLE_APPLICATION_CREDENTIALS: "/etc/credentials/gcp"
  GCP_DATASET: "dataset_example"
  GCP_TABLE_ID: "table_id_example"
  GCP_PROJECT_ID: "project_id_example"
  OCI_SHARED_CREDENTIALS_FILE: "/etc/credentials/oci"
  OCI_CLI_KEY_FILE: "/etc/credentials/oci_key_file.pem"
  API_PATH_PREFIX: "/api/cost-management"
  KOKU_API_HOSTNAME: "koku-server.{{ .Values.namespace }}.svc.cluster.local"
  KOKU_PORT: "8000"
  MASU_API_HOSTNAME: "masu-server.{{ .Values.namespace }}.svc.cluster.local"
  MASU_PORT: "5042"
  SOURCES_API_PORT: "3000"
  SOURCES_API_HOST: "sources-server"
  INSIGHTS_KAFKA_HOST: "kafka"
  INSIGHTS_KAFKA_PORT: "29092"
  KEEPDB: "True"
  PROMETHEUS_PUSHGATEWAY: "pushgateway:9091"
  AUTO_DATA_INGEST: "True"
  DEVELOPMENT_IDENTITY: '{"identity": {"account_number": "10001", "org_id": "1234567", "type": "User", "user": {"username": "user_dev", "email": "user_dev@foo.com", "is_org_admin": "True", "access": {}}},"entitlements": {"cost_management": {"is_entitled": "True"}}}'
  CACHED_VIEWS_DISABLED: "False"
  ACCOUNT_ENHANCED_METRICS: "False"
  ENHANCED_ORG_ADMIN: "True"
  DOCKER_BUILDKIT: "1"
  QE_SCHEMA: ""
  USER_ID: "999"
  GROUP_ID: "999"
