apiVersion: v1
kind: Service
metadata:
  name: masu-server
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: masu-server
  ports:
    - name: port1
      protocol: TCP
      port: 5042
      targetPort: 8000
    - name: port2
      protocol: TCP
      port: 5001
      targetPort: 9000
  type: ClusterIP
