apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trino-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 20Gi