apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-config
  namespace: {{ .Values.namespace }}
data:
  MY_NODE_ID: "localhost"
  LOCAL: "TRUE"
  TRINO_LOG_LEVEL: "INFO"
  TRINO_S3A_OR_S3: "s3a"
  MINIO_ENDPOINT: "http://minio.{{ .Values.namespace }}.svc.cluster.local:9000"
  S3_ACCESS_KEY: "kokuminioaccess"
  S3_SECRET: "kokuminiosecret"
  AWS_ACCESS_KEY_ID: "kokuminioaccess"
  AWS_SECRET_ACCESS_KEY: "kokuminiosecret"
  AWS_REGION: "us-east-1"
  S3_BUCKET_NAME: "koku-bucket"
  POSTGRES_SQL_SERVICE_HOST: "{{ .Values.database.postgresSQLServiceHost }}"
  POSTGRES_SQL_SERVICE_PORT: "{{ .Values.database.postgresSQLServicePort }}"
  DATABASE_NAME: "{{ .Values.database.databaseName }}"
  DATABASE_USER: "{{ .Values.database.databaseUser }}"
  DATABASE_PASSWORD: "{{ .Values.database.databasePassword }}"
