apiVersion: v1
kind: Service
metadata:
  name: koku-db
  namespace: {{ .Values.namespace }}
  labels:
    app: koku-db
spec:
  selector:
    app: koku-db
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP