apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - name: port1
      port: 9000
      targetPort: 9000
    - name: port2
      port: 9090
      targetPort: 9090
  selector:
    app: minio
