apiVersion: v1
kind: Service
metadata:
  name: create-parquet-bucket
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: create-parquet-bucket
