apiVersion: apps/v1
kind: Deployment
metadata:
  name: koku-db
  namespace: {{ .Values.namespace }}
  labels:
    app: koku-db
spec:
  replicas: {{ .Values.kokuDB.replicas }}
  selector:
    matchLabels:
      app: koku-db
  template:
    metadata:
      labels:
        app: koku-db
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: koku-db
          image: {{ .Values.kokuDB.image }}
          envFrom:
            - configMapRef:
                name: koku-db-config           
            - configMapRef:
                name: koku-config  
          ports:
            - containerPort: 5432
          command:
            - "postgres"
            - "-c"
            - "ssl=on"
            - "-c"
            - "ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem"
            - "-c"
            - "ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key"
            - "-c"
            - "max_connections=1710"
            - "-c"
            - "shared_preload_libraries=pg_stat_statements"
            - "-c"
            - "autovacuum_max_workers=8"
            - "-c"
            - "autovacuum_vacuum_cost_limit=4800"
            - "-c"
            - "autovacuum_vacuum_cost_delay=10"
            - "-c"
            - "max_locks_per_transaction=72"
            - "-c"
            - "pg_stat_statements.max=2000"
            - "-c"
            - "pg_stat_statements.save=off"
            - "-c"
            - "pg_stat_statements.track_utility=off"
            - "-c"
            - "track_activity_query_size=2048"
            - "-c"
            - "track_functions=pl"
            - "-c"
            - "log_min_error_statement=error"
            - "-c"
            - "log_min_duration_statement=2000"
            - "-c"
            - "logging_collector=on"
            - "-c"
            - "log_line_prefix=%t:%r:%u@%d:[%p]:"
            - "-c"
            - "log_statement=mod"
          livenessProbe:
            exec:
              command:
                - "pg_isready"
                - "--host=127.0.0.1"
                - "--port=5432"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - "pg_isready"
                - "--host=127.0.0.1"
                - "--port=5432"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
