apiVersion: v1
kind: ConfigMap
metadata:
  name: koku-db-config
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  _PG_CREATE_DATABASES: "postgres|postgres,unleash|postgres"
  POSTGRES_SQL_SERVICE_PORT: "5432"
  DATABASE_DATA_DIR: "postgresql"
  USER_ID: "999"
  GROUP_ID: "999"
