apiVersion: v1
kind: Secret
metadata:
  name: koku-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  aws: |
    [default]
    aws_access_key_id={{ .Values.credentials.awsAccessKeyId }}
    aws_secret_access_key={{ .Values.credentials.awsSecretAccessKey }}
  oci: |
    [DEFAULT]
    user={{ .Values.credentials.ociUser }}
    fingerprint={{ .Values.credentials.ociFingerprint }}
    tenancy={{ .Values.credentials.ociTenancy }}

