apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 8000 
      targetPort: 8000
      name: http
  selector:
    app: hive-metastore
#9083