apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-config
  namespace: {{ .Values.namespace }}
data:
  HIVE_LOGLEVEL: "INFO"
  S3_ENDPOINT: "http://minio.{{ .Values.namespace }}.svc.cluster.local:9000"
  S3_ACCESS_KEY: "{{ .Values.minioBucket.s3AccessKey }}"
  S3_SECRET: "{{ .Values.minioBucket.s3Secret }}"
  S3_BUCKET_NAME: "koku-bucket"
  S3_BUCKET_PATH: "data"
  POSTGRES_SQL_SERVICE_HOST: "{{ .Values.database.postgresSQLServiceHost }}"
  POSTGRES_SQL_SERVICE_PORT: "{{ .Values.database.postgresSQLServicePort }}"
  DATABASE_NAME: "{{ .Values.database.hiveDatabaseName }}"
  DATABASE_USER: "{{ .Values.database.hiveDatabaseUser }}"
  DATABASE_PASSWORD: "{{ .Values.database.hiveDatabasePassword }}"
