apiVersion: v1
kind: ConfigMap
metadata:
  name: koku-server-config
  namespace: {{ .Values.namespace }}
data:
  DATABASE_SERVICE_NAME: "{{ .Values.database.databaseServiceName }}"
  DATABASE_ENGINE: "{{ .Values.database.databaseEngine }}"
  DATABASE_NAME: '{{ .Values.database.databaseName | default "postgres" }}'
  POSTGRES_SQL_SERVICE_HOST: "{{ .Values.database.postgresSQLServiceHost }}"
  POSTGRES_SQL_SERVICE_PORT: "{{ .Values.database.postgresSQLServicePort }}"
  DATABASE_USER: '{{ .Values.database.databaseUser | default "postgres" }}'
  DATABASE_PASSWORD: '{{ .Values.database.databasePassword | default "postgres" }}'
  KOKU_SOURCES_CLIENT_HOST: "sources-client"
  KOKU_SOURCES_CLIENT_PORT: "9000"
  DJANGO_READ_DOT_ENV_FILE: "True"
  DEVELOPMENT: "True"
  SCHEMA_SUFFIX: ""
  TRINO_S3A_OR_S3: "s3a"
  RBAC_SERVICE_HOST: "rbac-server"
  RBAC_SERVICE_PORT: "9000"
  RBAC_SERVICE_PATH: "/r/insights/platform/rbac/v1/access/"
  REDIS_HOST: "koku-redis.{{ .Values.namespace }}.svc.cluster.local"
  REDIS_PORT: "6379"
  RBAC_CACHE_TTL: "300"
  PROMETHEUS_MULTIPROC_DIR: "/tmp"
  API_PATH_PREFIX: "/api/cost-management"
  MAX_GROUP_BY_OVERRIDE: "3"
  AWS_SHARED_CREDENTIALS_FILE: "/etc/credentials/aws"
  GOOGLE_APPLICATION_CREDENTIALS: ""
  OCI_SHARED_CREDENTIALS_FILE: "/etc/credentials/oci"
  OCI_CLI_KEY_FILE: "/etc/credentials/oci_key_file.pem"
  OCI_PYTHON_SDK_NO_SERVICE_IMPORTS: "True"
  DEMO_ACCOUNTS: ""
  ACCOUNT_ENHANCED_METRICS: "False"
  RUN_GUNICORN: ""
  POD_CPU_LIMIT: "1"
  GUNICORN_WORKERS: "3"
  GUNICORN_THREADS: "False"
  RETAIN_NUM_MONTHS: "4"
  NOTIFICATION_CHECK_TIME: "24"
  UNLEASH_HOST: "unleash.{{ .Values.namespace }}.svc.cluster.local"
  UNLEASH_PREFIX: "http"
  UNLEASH_PORT: "4242"
  UNLEASH_TOKEN: "{{ .Values.unleash.token }}"
  UNLEASH_LOG_LEVEL: "WARNING"
  QE_SCHEMA: ""
  ENHANCED_ORG_ADMIN: "True"
  TAG_ENABLED_LIMIT: "200"
  DELAYED_TASK_TIME: "20"
  DELAYED_TASK_POLLING_MINUTES: "5"
